### ISSUE TITLE
Point Recalculation

### ISSUE THREAD

**Issue by bleistivt** [hgtonight/Application-Yaga#102]
Not an issue, just leaving this here.

I saw that you had point recalculation as one of your plugin ideas:
https://github.com/hgtonight/Vanilla-Addons/blob/master/README.md

This is the query I have been using in the past:

``` sql
update GDN_User u set u.Points =
(
  select sum(a.AwardValue) from GDN_Reaction r
  inner join GDN_Action a on r.ActionID = a.ActionID
  where u.UserID = r.ParentAuthorID
) + (
  select sum(b.AwardValue) from GDN_BadgeAward ba
  inner join GDN_Badge b on ba.BadgeID = b.BadgeID
  where u.UserID = ba.UserID
)        

```

**Comment by hgtonight** [comment]
I will definitely be visiting this in the future.
