### ISSUE TITLE
"Level 1" Rank Rewarded Twice

### ISSUE THREAD

**Issue by austins** [hgtonight/Application-Yaga#104]
I'm using the default transport configuration. This seems to be present in 1.0.3 and with the current latest development code commits up to June 29, 2015.

When a new user joins or a user logs in for the first time since the application was enabled, they are rewarded the "Level 1" rank twice with two activities being posted saying they "earned a promotion to Level 1."

Could this be an issue with my configuration or a bug in the code?

**Comment by hgtonight** [comment]
Fixed by c3f5057a2e995aa747baa5f026dbfa7855727452
