### ISSUE TITLE
Idea: Reaction Record List for Activities

### ISSUE THREAD

**Issue by austins** [hgtonight/Application-Yaga#105]
On the activities page, I was thinking it would look great to have a reaction record list, like the one under discussion posts and comments, that shows avatars of users who clicked on a reaction. The reaction choices list could also be displayed without requiring a mouse hover as well if this were the case.

What do you all think?

**Comment by hgtonight** [comment]
Not sure.

I originally didn't include the record to mirror what the hosted version of Reactions does (not) do.

I would accept a PR that adds the reaction record to Activity items with defaulting to be off.
