### ISSUE TITLE
Look into optimization / scaling of ActedModel

### ISSUE THREAD

**Issue by bleistivt** [hgtonight/Application-Yaga#116]
Getting a lot of errors like this:

    [30-Nov-2015 00:56:28 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /www/htdocs/vanilla-master/applications/yaga/models/class.actedmodel.php on line 372

These are the "Best Of" pages. I am not using those, but they also timeout frequently.
The forum has 50k comments and 20k reactions (reactions growing at a much faster rate though).

#79 has helped with memory consumption, but profile/reactions will have the same problem in the future.

A table for items with reactions (discussions, comments, activity) may solve that problem.

**Comment by hgtonight** [comment]
What did you mean by a table for items with reactions?

**Comment by bleistivt** [comment]
Something like this:
(ParentID, ParentType, DateInserted, ActionID)

A table that stores 1 entry for every 1or more reactions of a type that an item receives.

An item () with 3 reactions, 2 of ID 5 and one of ID 7 would result in 2 entries:
(123, comment, 2016-02-03..., 5)
(123, comment, 2016-02-03..., 7)

Since this table would store the date of the item (which doesn't change) and group by reaction type, you could paginate using the database. This would remove the need to fetch the entire reaction table everytime which is the weakness of the current approach.

The downside is that this table would consist entirely of denormalized data and would thus need a dba/counts method. To implement the security (category permissions) filter you would also need to "overquery" to prevent empty pages.

**Comment by hgtonight** [comment]
I just added a new index to the reactions table via #127 

Would you mind testing this for me?

**Comment by bleistivt** [comment]
Adding the index works, but I'm still getting the timeout.
In my case, the new index has the same cardinality as the primary key, so overlapping `ParentID`s don't seem to be the problem at all (since they are so rare/nonexistent anyway, it should already optimize that).

**Comment by bleistivt** [comment]
Found that the slowness came from calling `ksort` hundreds of times.

**Comment by hgtonight** [comment]
Thanks!

Closed by #129
