### ISSUE TITLE
Activities Absolute/Relative Paths

### ISSUE THREAD

**Issue by austins** [hgtonight/Application-Yaga#117]
The commit in the develop branch that changes the badge photo path from a relative path to an absolute path, 02fca4f4763b1c2a478a29bd2b8b5978b699a018, causes issues as described below.

* The absolute path that had been stored in the Activity table in the database contains the full site URL with the scheme, so the browser outputs an insecure resource error when badge activities are loaded on the page for sites that change from http to https.
* On a related note, absolute paths will cause the images to not get loaded if the Vanilla install were moved to another directory on the server.

For this reason, I suggest we stick with relative paths in the format of `/uploads/yaga/NameOfPhoto.jpg` so that if the Vanilla installation is moved or changed from http to https, the badge photos still get loaded up.

What is the notifications popin issue? Is it possible to make the notifications popin convert relative paths to absolute paths using the url() function in the core file and submit a pull request for it to the official Vanilla repo instead of while creating the activity via Yaga, or is there another way to resolve the notifications popin issue?

By the way, as of January 5, 2016, rank activities still use relative paths for photos, at least with the defaultTransport configuration we have the config setting `$Configuration['Yaga']['Ranks']['Photo'] = '/uploads/yaga/NameOfPhoto.jpg';` and the activity that gets created in RankModel->Set() doesn't call the url() function. If you wish to keep absolute paths, should rank activities be updated as well?

This is a rare occurrence though, so this may not be an issue and databases could just have a search and replace done on them.

---

Unrelated to the issue, but may be interesting to know: there is indeed another activity that uses absolute paths. For example, the dashboard activity that has the `HeadlineFormat` of `{RegardingUserID,You} changed {ActivityUserID,your} profile picture.` has a `Story` that includes an img that uses the absolute path to the uploads folder, and it doesn't use the `Photo` column since it displays the user image already, with the specific user image it's referring to in the story. The Vanilla team could probably update this activity to make use of the data attributes to store a relative path and render it via the view using a function to handle this specific activity type, but that's if absolute paths are a big issue.

Advanced Editor image uploads have absolute paths for them as well. So, this may be something we can live with. Absolute paths are not that big of a deal.

**Comment by hgtonight** [comment]
I could have sworn most activities used absolute paths.

I noticed this when I was working on [Firefox-Vanilla-Notifier](https://github.com/hgtonight/Firefox-Vanilla-Notifier). Do you know if they support protocol-less links (i.e. starting with `//`)?

**Comment by hgtonight** [comment]
Closed without more feedback

**Comment by x00** [comment]
Activities should not use absolute paths for photos. It is not portable and cause mixed content errors.
