### ISSUE TITLE
Error when first Rank is reached.

### ISSUE THREAD

**Issue by blackstalk** [hgtonight/Application-Yaga#118]
Hi, I'm getting this error when a rank is reached, Any Idea? Thanks, regards -Hochoa
![screen shot 2016-01-15 at 12 25 01 pm](https://cloud.githubusercontent.com/assets/2893908/12397608/84a7a70c-bdcb-11e5-843b-4d5a314330b9.png)

**Comment by hgtonight** [comment]
What version of Yaga are you using?

What version of Vanilla?

**Comment by blackstalk** [comment]
YAGA Version 1.0.3, Vanilla 2.1.11

**Comment by hgtonight** [comment]
That is a notice, not an error.

I will correct this in Yaga 1.1.

Thanks for the report!

**Comment by hgtonight** [comment]
Actually, this is already fixed in the development version: 6f7bbb00bc6868ef03c6479372359a5d9f93525d
