### ISSUE TITLE
Add pretty URL check on setup to prevent common issues

### ISSUE THREAD

**Issue by hgtonight** [hgtonight/Application-Yaga#135]
Broken activity links could be solved by not allowing to enabled if rewrite urls is false.

**Comment by bleistivt** [comment]
Shouldn't this be transparent if url() and asset() is used everywhere?

**Comment by hgtonight** [comment]
Should be.

I remember making the decision to require pretty URLs but I can't remember
why.

**Comment by hgtonight** [comment]
Closed in favor of #149
