### ISSUE TITLE
Custom configs from rank must not be applied in the Settings

### ISSUE THREAD

**Issue by R-J** [hgtonight/Application-Yaga#139]
All custom rank configs are always applied to the user. If the user is an admin or mod and wants to change config settings, he gets shown the config settings based on his rank, which is false.

e.g. the "Edit Timeout" can be set based on ranks. If the default setting for "EditContentTimeout" is "never edit" and the admin has a level with "always edit", he would see that level specific config on the Forum/Advanced page, which is not only confusing, but also dangerous: if the admin only wants to change the number of discussions, he might not note that he will also change the "never edit" setting to his role specific "always edit"

**Comment by hgtonight** [comment]
This is interesting. The only way around this is to temporarily suspend config perks while in the dashboard.

I can't think of an elegant way to do this, do you?

**Comment by R-J** [comment]
I'm working on it. My first attempt has been to do something like that:

~~~
public function settingsController_render_before($sender, $args) {
    // drop config from cache and re-load it
~~~
But I haven't found a way to reload the config.

<hr> 

A workaround would be to change your
~~~
  private function _ApplyCustomConfigs($Name = NULL, $Value = NULL) {
    SaveToConfig($Name, $Value, array('Save' => FALSE));
  }
~~~
and add a  `SaveToConfig('YAGABackup'.$Name, $Value, array('Save' => FALSE));`
After that you would be able to restore the config settings in settings_render_before().

<hr>

Instead of letting YAGA change the value and resetting it sometime afterwards would be to not change the config at all, by adding some kind of Gdn::request() parsing, but nothing of that is elegant...
