### ISSUE TITLE
Form->InputPrefix is deprecated

### ISSUE THREAD

**Issue by R-J** [hgtonight/Application-Yaga#146]
The BadgeControllers Edit() method tries to fetch the rules form fields based on a prefix "_Rules" before the form fields. 
The RulesControllers GetCriteriaForm() supplies the forms through an AJAX call. Before the FormString gets built, Form->InputPrefix is set to "_Rules" in order to prefix every form field.

But InputPrefix has been deprecated. That's why there is no prefix any more before the form field names and therefore they cannot be found.

This is the reason for this error https://github.com/hgtonight/Application-Yaga/issues/142

I see four ways to react on that:
1. Change all rules to incorporate a `['name' =>'_Rules/ElementName']` attribute. That way no logic would have to be changed. The downside is that people with custom rules may face problems.
2. Prefix all other form field with something like "BadgeEdit_" by changing the edit view and change the logic in the Edit() method from `if(substr($Key, 0, 7) == '_Rules/') {` to  `if(substr($Key, 0, 10) != 'BadgeEdit_') {`. You would only have to change two files then and everything else could stay the same.
3. Pass all FormValues to the YagaRules Validate() method. But if any form field of a rule would have the same name as a form field of the edit view, you would get unpredictable errors.
4. A magician like you would most probably be able to extend/replace the form class with a thin wrapper that would add a name attribute to every call. Although I think that this would be quite cool, I'd also say that this is overkill...

**Comment by steam1** [comment]
R-J asi funciona ! 
Saludos

if(substr($Key, 0, 10) != 'BadgeEdit_') { 
          //$RealKey = substr($Key, 7);
          $Criteria[$Key] = $Value;
 }

**Comment by HIAviator** [comment]
By implementing #2 would you not have to also trim the "BadgeEdit_" prefix off the front of the other form values so that they store correctly?

**Comment by R-J** [comment]
I hope you are asking @steam1 and not me, since I never really made those changes but was just thinking about how that could be done...

**Comment by HIAviator** [comment]
For now I've hard coded the rules and perks fields in manually which works for my own implementation to get it working.  @steam1 could you let me know if you have a more flexible solution done?

**Comment by R-J** [comment]
[That one](https://github.com/hgtonight/Application-Yaga/pull/148) is less invasive, though far from being elegant... :-(

**Comment by hgtonight** [comment]
Closed by #148
