### ISSUE TITLE
Badge display problems with Safari

### ISSUE THREAD

**Issue by romeojulietthotel** [hgtonight/Application-Yaga#154]
```html
<img src="/applications/yaga/design/images/default_badges.svg#portrait-upload" class="BadgePhotoDisplay">
```

I think that using img tags might be why badges don't display correctly with Safari. 
and more specifically it may be related to the `#portrait-upload`  _(or whatever follows the src=, for example it could also be #comment-1)_

When I load the full url into Safari the badge displays correctly. Like this:

`https://www.example.com/applications/yaga/design/images/default_badges.svg#portrait-upload`

Not sure if this is a PHP issue in how it treats the src url or if it is the <img> tag.

I've looked around and there's a ton of info but I couldn't nail anything down.
I've seen suggestions to use <object> or <embed> or <iframe> tags.

I am pretty sure there are performance trade-offs by specifying the full url. i.e. 
`https://www.example.com/applications/yaga/design/images/default_badges.svg#portrait-upload`

I have checked the mime type for svg and it is sent correctly as svg+xml.

**Comment by hgtonight** [comment]
If the SVG fragment identifier works when going to the full URL, I suspect this is a server configuration issue. That is, unless it works as expected on Firefox or Chrome.

**Comment by romeojulietthotel** [comment]
The badges appear correctly on Vivaldi (like chrome) and Firefox.

**Comment by hgtonight** [comment]
Looks like Safari doesn't support it: http://caniuse.com/#feat=svg-fragment

If you can come up with a fallback, I would consider including it.

**Comment by romeojulietthotel** [comment]
That's interesting. I had looked at caniuse but didn't know the magic word here (svg-fragment).

I'll look into a fallback.

**Comment by romeojulietthotel** [comment]
I found a solution that works on Safari, Safari Preview, Vivaldi and Firefox and also Linux Firefox.  

I changed '<img src=' tags to use object tags instead.

```html
<object data="default_badges.svg#running-man" type="image/svg+xml">
  (some fallback could go here and could be a raster image uri/url)
  </object>
```
