### ISSUE TITLE
Reaction sprites not visible on MacOS.

### ISSUE THREAD

**Issue by romeojulietthotel** [hgtonight/Application-Yaga#155]
The react sprites that should be visible under a comment are not visible with Safari or Vivaldi (like chrome) or Firefox on MacOS.

If I look at the source the entire `<span>` tag is missing.  i.e.
This appears: 

`<div class="Reactions">`

But this does not and everything in the `<span>` after to define the ReactMenu does not:

`<span class="ReactMenu">`

Only this is there:

```html
<div class="ReactionRecord"></div><div class="Reactions"></div>            </div>
```

That last `</div>` closes Item-Body div.

**Comment by hgtonight** [comment]
And the appropriate markup exists on another operating system?

**Comment by romeojulietthotel** [comment]
Yep, it looks and works fine with Firefox on Linux. (The server's ok :) )

**Comment by romeojulietthotel** [comment]
Your question now makes me rethink this.  I can see the Reaction sprites/images on MacOS but cannot see them on Linux!  What's going on?  Is it another plugin causing problems?  Far as I know this web server's a standard apache setup running PHP7.

**Comment by romeojulietthotel** [comment]
Alright, I am wasting your time, apologies. This looks like a permissions problem. Not sure but possibly users that exist don't get permissions for this feature while users created after do by default. I'm thinking out loud.  I'll go look into this more closely now.
