### ISSUE TITLE
Autoloader needs to be started manually (Vanilla 2.4)

### ISSUE THREAD

**Issue by bleistivt** [hgtonight/Application-Yaga#156]
It looks like ``Gdn_Autoloader::start()`` is not being called in core anymore.

This makes the ``RegisterMap`` call throw a few notices.

just adding: ``Gdn_Autoloader::start();`` before this...
https://github.com/hgtonight/Application-Yaga/blob/master/settings/bootstrap.php#L9
... fixes it, so does adding it to bootstrap.early.php.

However, this feels like a hack as it seems like Gdn_Autoloader is deprecated in favor of composers autoloader.

**Comment by hgtonight** [comment]
I wonder how hard it is to hook into composer's auto loader
