### ISSUE TITLE
User Permissions for using Reactions

### ISSUE THREAD

**Issue by aminemarref** [hgtonight/Application-Yaga#167]
Hello,

I am using Yaga with Vanilla open-source version 2.5.2. I would like to enable all users to use reactions. 

Inside "Gamification -> Reactions -> Edit Action", I see the menu "Permission" with the description "A user will need the following permission to use this action. The default is 'Yaga.Reactions.Add'". However, I have no idea which permission to set to enable all registered users to "react".

My question: Which permission setting do I choose to enable any registered user in my forum to react using the Yaga application?

Any help is very much appreciated.

Regards,
Amine.

**Comment by bleistivt** [comment]
Yes, the defaults should work fine. When in doubt, just create a test account with user permissions.

**Comment by aminemarref** [comment]
Thank you :-)

I am still not getting it. I have test users which under "Moderation -> Site -> Users" have the role "member". These users are unable to "react" when logged in. Only the user with "Administrator" role can perform Reactions.

I feel I missing something... You said "create a test account with user permissions". What permissions if you don't mind?

**Comment by aminemarref** [comment]
Never mind, I found it :-)
My bad...
