### ISSUE TITLE
Orphan reaction records

### ISSUE THREAD

**Issue by bleistivt** [hgtonight/Application-Yaga#62]
When a post or discussion is deleted, the associated reaction records are not.
This leads to wrong reaction counts ~~and trailing empty pages in profile/reactions.~~

**Comment by hgtonight** [comment]
Deleting discussions shouldn't remove reactions that award <= 0 points to prevent trolling intentionally and then deleting the discussion.

I would say that upon deletion of the UGC, Yaga should null the parent type, id, and author in the reaction table for associated reactions.

Does this make sense to you?

**Comment by bleistivt** [comment]
Yes. After thinking some more about it a fix only adressing the pager issue may already be suffient, too.
