### ISSUE TITLE
Reactions are restricted

### ISSUE THREAD

**Issue by hgtonight** [hgtonight/Application-Yaga#75]
It is pretty difficult to get reactions on content that doesn't conform to standard Vanilla types.

I want to make it easy for custom types to accept reactions.

This will require rethinking the acted model and best controllers.

I am thinking something like:

    echo Yaga::RenderReactionRecord($ID, $Type);
    echo Yaga::RenderReactionList($ID, $Type);

This would allow plugins to put their own checks in terms of permissable requirements.

Will require an event in at least the reaction model.

**Comment by bleistivt** [comment]
Recently did some tests:
Adding another enum like this

`->Column('ParentType', array('discussion', 'comment', 'activity', 'new'), true)`

...doesn't really work: all rows of the "new" type will be set to null on the next structure update (I tried this in the Structure() method and using the Gdn_MySQLStructure_BeforeSet_Handler)

This would also allow for only a single new type.

New content types would probably require a table.

**Comment by hgtonight** [comment]
I was think more to make parent type a varchar field and fire an event if
the core can't handle the type.

Thoughts?

**Comment by bleistivt** [comment]
:+1: 

Looks like converting from enum to varchar works without problems.

**Comment by bleistivt** [comment]
It's all pretty straight forward until it gets to the ActedModel :neutral_face: 

This is the least invasive way I could think of:
https://github.com/hgtonight/Application-Yaga/compare/master...bleistivt:patch-6

(I'll report back once I know if it actually works...)

**Comment by bleistivt** [comment]
Just tested it, handling a new reaction type is very easy

    public function ReactController_UnknownType_Handler($Sender, &$Args) {
        if ($Args['TargetType'] == 'article') {
            $Model = new ArticleModel();
            $Args['Item'] = $Model->GetByID($Args['TargetID']);
            $Args['ItemOwnerID'] = val('InsertUserID', $Args['Item']);
        }
    }

...then this works without problems:

    echo RenderReactionRecord($ID, 'article');
    echo RenderReactionList($ID, 'article');
    
When adding the content to the ActedModel, the User is responsible for fetching the content in the `Content` Hook and then preparing it for display in the `UnknownRecordType` Hook.

I moved everything that is comment/discussion-specific in a condition, so it doesn't interfere.

Let me know what you think.

**Comment by hgtonight** [comment]
I think this is awesome! +1

I have a few suggestions, but I think this needs to be a pull request to comment on line by line.

**Comment by hgtonight** [comment]
Is the patch-6 branch still your working copy?

**Comment by bleistivt** [comment]
Great! I'l squash the branch into a commit tomorrow.
