### ISSUE TITLE
Pager

### ISSUE THREAD

**Issue by wolfgang1** [hgtonight/Application-Yaga#78]
The pager (more, less) doesn't display on my site. Also if I change the theme to the default one.
I'm using the last GitHub version with vanilla 2.1.6.

Best of all time page on my forum (the theme is bootstrap, but it doesn't work also with the default vanilla theme. I've also installed infinite scrolling plugin but it doesn't work also if I disable it):
http://www.spazioasperger.it/forum/best/alltime

**Comment by hgtonight** [comment]
Sorry for the long delay.

What pager isn't working?
