### ISSUE TITLE
guest reactions permitted, causing warnings on display. 

### ISSUE THREAD

**Issue by replyPUSH** [hgtonight/Application-Yaga#86]
https://github.com/hgtonight/Application-Yaga/blob/master/controllers/class.reactcontroller.php#L79

will allow for `UserID = 0`

later on on display you use `Gdn::UserModel()->GetID($Reaction->UserID);` This user doesn't exist so neither do its properties. 

Turn debug notices on they are helpful, in trapping this type of bug.

**Comment by x00** [comment]
sorry posted under wrong user.

**Comment by x00** [comment]
guest reactions would be widely open to abuse anyway.

**Comment by x00** [comment]
for some reason it is has only created the view permissions. There are no Add permissions for roles.

**Comment by x00** [comment]
I eliminated the problem by forcing the running of structure.

**Comment by hgtonight** [comment]
This was due to an upgrade without running the structure update?

**Comment by x00** [comment]
I don't think so, though someone had messed with the version.
