### ISSUE TITLE
Deleting ranks causes fatal error

### ISSUE THREAD

**Issue by x00** [hgtonight/Application-Yaga#94]
https://github.com/hgtonight/Application-Yaga/blob/master/settings/class.hooks.php#L463

PR shortly

**Comment by hgtonight** [comment]
Was this fixed?

I am not seeing the issue presently.

**Comment by x00** [comment]
you just need to check that

`$Perks = $RankModel->GetPerks($RankID);` produces something that can been looped.

**Comment by hgtonight** [comment]
Thanks for the follow up.

This was already fixed in: 6f7bbb00bc6868ef03c6479372359a5d9f93525d
