### ISSUE TITLE
Use new locale conventions

### ISSUE THREAD

**Issue by bleistivt** [hgtonight/Application-Yaga#96]
Notice 	Locales in /applications/yaga/locale/de-DE/definitions.php is deprecated. Use /applications/yaga/locale/de-DE.php instead. in Z:\web\vanilla-master\library\core\class.locale.php line 253
    Notice 	Locales in /applications/yaga/locale/en-CA/definitions.php is deprecated. Use /applications/yaga/locale/en-CA.php instead. in Z:\web\vanilla-master\library\core\class.locale.php line 253
    Notice 	Locales in /applications/yaga/locale/pt-BR/definitions.php is deprecated. Use /applications/yaga/locale/pt-BR.php instead. in Z:\web\vanilla-master\library\core\class.locale.php line 253

**Comment by bleistivt** [comment]
#97 just noticed you can rename from the web interface

**Comment by hgtonight** [comment]
Closed by #98

**Comment by hgtonight** [comment]
It says to use `de-DE.php` instead of `de.php`.

Any reason you used `de.php`?

**Comment by bleistivt** [comment]
I based this on https://github.com/vanilla/locales where they have a new `de` locale and marked de-DE as deprecated.

**Comment by hgtonight** [comment]
The merge borked my 2.1 install.

**Comment by bleistivt** [comment]
Is it because of the locale?

I assumed you were targeting 2.2, because you merged #89 which requires 2.2

**Comment by hgtonight** [comment]
I did test it (against a 2.2 install) but I didn't fully read your PR notes.

I wanted to support 2.1 in case of a protracted 2.2 beta period like 2.1.

Guess I should just have 1.1 target 2.2.

**Comment by bleistivt** [comment]
if you want to release a new version earlier, it could also be rewritten to

```php
// Save the uploaded image
$Parts = $Upload->SaveAs($TmpImage, 'yaga' . DS . $ImageBaseName);
$RelativeUrl = StringBeginsWith($Parts['Url'], Gdn_Url::WebRoot(TRUE), TRUE, TRUE);
if (method_exists('Gdn_Request', 'UrlDomain')) {
    $AssetRoot = Gdn::Request()->UrlDomain(TRUE).Gdn::Request()->AssetRoot();
    $RelativeUrl = StringBeginsWith($Parts['Url'], $AssetRoot, TRUE, TRUE);
}

```

**Comment by hgtonight** [comment]
Yaga 1.1 will not support 2.1.
